import { THEME_COLORS, COMPONENT_SIZES, BORDER_RADIUS, ELEVATION } from './theme'

export const BUTTON_COLORS = THEME_COLORS
export const BUTTON_SIZES = COMPONENT_SIZES
export const BUTTON_ROUNDED = BORDER_RADIUS
export const BUTTON_ELEVATION = ELEVATION